import { execute } from "~/lib/db";

const reset = async () => {
  const query = `
    DROP TABLE IF EXISTS "STUDENT" CASCADE;
    DROP TABLE IF EXISTS "JOB_ANNOUNCER" CASCADE;
    DROP TABLE IF EXISTS "KUSD" CASCADE;
    DROP TABLE IF EXISTS "APPROVED_COMPANY" CASCADE;
    DROP TABLE IF EXISTS "JOB_ANNOUNCEMENT" CASCADE;
    DROP TABLE IF EXISTS "POSITION" CASCADE;
    DROP TABLE IF EXISTS "EVALUATION" CASCADE;
    DROP TABLE IF EXISTS "QUALIFICATION_ANNOUNCEMENT" CASCADE;
    DROP TABLE IF EXISTS "EXAMINATION" CASCADE;
    DROP TABLE IF EXISTS "QUALIFICATION_ANNOUNCEMENT" CASCADE;
    DROP TABLE IF EXISTS "JOB_RECRUIT" CASCADE;
    DROP TABLE IF EXISTS "TAG" CASCADE;
    DROP TABLE IF EXISTS "RELATION_TAGGED" CASCADE;
    DROP TABLE IF EXISTS "RELATION_RECEIVE_QUALIFICATION" CASCADE;
    DROP TABLE IF EXISTS "RELATION_PROVIDE_EXAM" CASCADE;
    DROP TABLE IF EXISTS "RELATION_VALIDATE" CASCADE;
    DROP TABLE IF EXISTS "RELATION_TAGGED" CASCADE;
`;
  await execute(query);
  console.log("Reset database successfully");
  process.exit(0);
};

reset();
